# CMake generated Testfile for 
# Source directory: D:/GemmaFit/native
# Build directory: D:/GemmaFit/native/build_local
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_com_tracker "D:/GemmaFit/native/build_local/Debug/test_com_tracker.exe")
  set_tests_properties(test_com_tracker PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;81;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_com_tracker "D:/GemmaFit/native/build_local/Release/test_com_tracker.exe")
  set_tests_properties(test_com_tracker PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;81;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_com_tracker "D:/GemmaFit/native/build_local/MinSizeRel/test_com_tracker.exe")
  set_tests_properties(test_com_tracker PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;81;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_com_tracker "D:/GemmaFit/native/build_local/RelWithDebInfo/test_com_tracker.exe")
  set_tests_properties(test_com_tracker PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;81;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
else()
  add_test(test_com_tracker NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_safety_monitor "D:/GemmaFit/native/build_local/Debug/test_safety_monitor.exe")
  set_tests_properties(test_safety_monitor PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;82;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_safety_monitor "D:/GemmaFit/native/build_local/Release/test_safety_monitor.exe")
  set_tests_properties(test_safety_monitor PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;82;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_safety_monitor "D:/GemmaFit/native/build_local/MinSizeRel/test_safety_monitor.exe")
  set_tests_properties(test_safety_monitor PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;82;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_safety_monitor "D:/GemmaFit/native/build_local/RelWithDebInfo/test_safety_monitor.exe")
  set_tests_properties(test_safety_monitor PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;82;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
else()
  add_test(test_safety_monitor NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_kinematics_pipeline "D:/GemmaFit/native/build_local/Debug/test_kinematics_pipeline.exe")
  set_tests_properties(test_kinematics_pipeline PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;83;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_kinematics_pipeline "D:/GemmaFit/native/build_local/Release/test_kinematics_pipeline.exe")
  set_tests_properties(test_kinematics_pipeline PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;83;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_kinematics_pipeline "D:/GemmaFit/native/build_local/MinSizeRel/test_kinematics_pipeline.exe")
  set_tests_properties(test_kinematics_pipeline PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;83;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_kinematics_pipeline "D:/GemmaFit/native/build_local/RelWithDebInfo/test_kinematics_pipeline.exe")
  set_tests_properties(test_kinematics_pipeline PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;83;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
else()
  add_test(test_kinematics_pipeline NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_motion_quality "D:/GemmaFit/native/build_local/Debug/test_motion_quality.exe")
  set_tests_properties(test_motion_quality PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;84;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_motion_quality "D:/GemmaFit/native/build_local/Release/test_motion_quality.exe")
  set_tests_properties(test_motion_quality PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;84;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_motion_quality "D:/GemmaFit/native/build_local/MinSizeRel/test_motion_quality.exe")
  set_tests_properties(test_motion_quality PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;84;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_motion_quality "D:/GemmaFit/native/build_local/RelWithDebInfo/test_motion_quality.exe")
  set_tests_properties(test_motion_quality PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;84;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
else()
  add_test(test_motion_quality NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_subject_selector "D:/GemmaFit/native/build_local/Debug/test_subject_selector.exe")
  set_tests_properties(test_subject_selector PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;85;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_subject_selector "D:/GemmaFit/native/build_local/Release/test_subject_selector.exe")
  set_tests_properties(test_subject_selector PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;85;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_subject_selector "D:/GemmaFit/native/build_local/MinSizeRel/test_subject_selector.exe")
  set_tests_properties(test_subject_selector PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;85;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_subject_selector "D:/GemmaFit/native/build_local/RelWithDebInfo/test_subject_selector.exe")
  set_tests_properties(test_subject_selector PROPERTIES  _BACKTRACE_TRIPLES "D:/GemmaFit/native/CMakeLists.txt;78;add_test;D:/GemmaFit/native/CMakeLists.txt;85;add_kinematics_test;D:/GemmaFit/native/CMakeLists.txt;0;")
else()
  add_test(test_subject_selector NOT_AVAILABLE)
endif()
